from composio_agno import Action


gmail_tools_actions = [
    Action.GMAIL_FETCH_EMAILS, 
    Action.GMAIL_CREATE_EMAIL_DRAFT,
    Action.GMAIL_ADD_LABEL_TO_EMAIL,
    Action.GMAIL_CREATE_LABEL,
    Action.GMAIL_DELETE_DRAFT,
    Action.GMAIL_DELETE_MESSAGE,
    Action.GMAIL_FETCH_MESSAGE_BY_MESSAGE_ID,
    Action.GMAIL_FETCH_MESSAGE_BY_THREAD_ID,
    Action.GMAIL_GET_ATTACHMENT,
    Action.GMAIL_GET_CONTACTS,
    Action.GMAIL_GET_PEOPLE,
    Action.GMAIL_GET_PROFILE,
    Action.GMAIL_LIST_DRAFTS,
    Action.GMAIL_LIST_LABELS,
    Action.GMAIL_LIST_THREADS,
    Action.GMAIL_MODIFY_THREAD_LABELS,
    Action.GMAIL_MOVE_TO_TRASH,
    Action.GMAIL_REMOVE_LABEL,
    Action.GMAIL_REPLY_TO_THREAD,
    Action.GMAIL_SEARCH_PEOPLE,
    Action.GMAIL_SEND_EMAIL
    ]

calendar_tools_actions = [
    Action.GOOGLECALENDAR_CREATE_EVENT,
    Action.GOOGLECALENDAR_DELETE_EVENT,
    Action.GOOGLECALENDAR_DUPLICATE_CALENDAR,
    Action.GOOGLECALENDAR_FIND_EVENT,
    Action.GOOGLECALENDAR_FIND_FREE_SLOTS,
    Action.GOOGLECALENDAR_GET_CALENDAR,
    Action.GOOGLECALENDAR_GET_CURRENT_DATE_TIME,
    Action.GOOGLECALENDAR_LIST_CALENDARS,
    Action.GOOGLECALENDAR_PATCH_CALENDAR,
    Action.GOOGLECALENDAR_PATCH_EVENT,
    Action.GOOGLECALENDAR_QUICK_ADD,
    Action.GOOGLECALENDAR_REMOVE_ATTENDEE,
    Action.GOOGLECALENDAR_SYNC_EVENTS,
    Action.GOOGLECALENDAR_UPDATE_EVENT
]

weather_tools_actions = [Action.WEATHERMAP_WEATHER]

search_tools_actions = [
    Action.COMPOSIO_SEARCH_DUCK_DUCK_GO_SEARCH,
    Action.COMPOSIO_SEARCH_EVENT_SEARCH,
    Action.COMPOSIO_SEARCH_EXA_SIMILARLINK,
    Action.COMPOSIO_SEARCH_FINANCE_SEARCH,
    Action.COMPOSIO_SEARCH_GOOGLE_MAPS_SEARCH,
    Action.COMPOSIO_SEARCH_IMAGE_SEARCH,
    Action.COMPOSIO_SEARCH_NEWS_SEARCH,
    Action.COMPOSIO_SEARCH_SCHOLAR_SEARCH,
    Action.COMPOSIO_SEARCH_SEARCH,
    Action.COMPOSIO_SEARCH_SHOPPING_SEARCH,
    Action.COMPOSIO_SEARCH_TAVILY_SEARCH,
    Action.COMPOSIO_SEARCH_TRENDS_SEARCH
]
